[package]
name = "command-line-tool-explore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.0"
cmd_lib = "1.3.0"
regex = "1.7.1"
version-compare = "0.1.1"